export { default as Login } from './Login'
export { default as Cadastrar } from './Cadastrar'
export { default as Home } from './Home'
export { default as Animal } from './Animal'
export { default as Castra } from './Castra'
export { default as Vacina } from './Vacina'
export { default as Camera } from './Camera'
